<a href="https://colab.research.google.com/github/rvikunwar/KNN/blob/main/KNN_for_IRIS_dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix

In [2]:
data=load_iris()

In [3]:
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [5]:
df=pd.DataFrame(np.c_[data.data,data.target])

In [9]:
df.tail()

0    1    2    3    4
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

In [10]:
df.shape

(150, 5)

In [11]:
x,y = df.iloc[:,0:-1],df.iloc[:,-1]

In [12]:
print(y)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: 4, Length: 150, dtype: float64


In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2020)

In [49]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [50]:
classifier.fit(x_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [51]:
classifier.score(x_test,y_test)

0.9

In [52]:
y_predict=classifier.predict(x_test)


In [64]:
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]


In [59]:
df_1=pd.DataFrame(data=cm,index=['setosa','versicolor','virginica'],columns=['setosa','versicolor','virginica'])

In [60]:
df_1

setosa  versicolor  virginica
setosa          10           0          0
versicolor       0           9          1
virginica        0           2          8

In [62]:
df_2=pd.DataFrame(np.c_[y_predict,y_test],columns=['y_predict','y_test'])

In [63]:
df_2

y_predict  y_test
0         2.0     2.0
1         0.0     0.0
2         1.0     1.0
3         1.0     1.0
4         1.0     1.0
5         1.0     2.0
6         2.0     2.0
7         1.0     1.0
8         0.0     0.0
9         0.0     0.0
10        2.0     2.0
11        1.0     2.0
12        0.0     0.0
13        2.0     2.0
14        2.0     2.0
15        0.0     0.0
16        1.0     1.0
17        1.0     1.0
18        2.0     2.0
19        0.0     0.0
20        0.0     0.0
21        2.0     2.0
22        2.0     1.0
23        0.0     0.0
24        2.0     2.0
25        1.0     1.0
26        1.0     1.0
27        1.0     1.0
28        0.0     0.0
29        0.0     0.0